language: node_js
sudo: false
node_js:
- lts/*
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: aleRoks7zUxmElRA2XNIVfWYzw70YMt1DcIUmm1otnRki6p6VcyJcfJiyy8dbDnShM6u7dfjsLvKyOM8PDkIAhvFHlC6tcxqv8VZQ1Jg33I6bTPvNaLQnQJAPxIgMIe+MdJbOqlsPZC6g/HzqFqWjwn+jzYXyH2Y8+K5BLWYhVw=
  on:
    tags: true
    repo: noflo/noflo-nodejs
  skip_cleanup: true
